### ISSUE TITLE
Critical: Nested resources are still accessible

### ISSUE THREAD

**Issue by Zaijo** [ryanb/cancan#1014]
Following the original guidline in CanCan wiki - [Nested Resources](https://github.com/ryanb/cancan/wiki/Nested-Resources) leads to unwanted behaviour. 

CanCan checks access rights for project given in `params[:project_id]`. It means, that there is still a possibility of bypassing the check for tasks. Consider we have read access to project #5. Navigating to `projects/5/tasks/47` will **show** task 47 no matter what is it's parent project.

To fix this, always set the following in a before_filter

``` ruby
@project = @task.project if @task
```

I updated the wiki page, but i need your consent for such advice to public.
Many sites might be vulberable this way.

**Comment by dkonayuki** [comment]
I figured out how to fix this. By adding these in index action, instead of `load_and_authorize_resource`:

    educations = @user.educations
    authorize! :index, educations
