### ISSUE TITLE
Hability in hstore

### ISSUE THREAD

**Issue by emerak** [ryanb/cancan#1024]
I have this in my form, comments in an hstore field that is in riskmatrix model, at this moment the field comment is disabled

   = riskmatrix.simple_fields_for :comments, defaults: { ability: true, action: action_name } do |comment|
        = comment.input :comment, label: t('riskmatrix.comments'), input_html: { disabled: false }, required: false

and this in my ability file

```
  can [:create, :update, :show], :riskmatrices
```

I cant get this to be enabled, I dont know why, when I remove the rule and simply add :access, :all the fields enable, but I just want comment to be enable, am I doing something wrong, there's any other thing I should do with Hstore ?

**Comment by Lujaw** [comment]
+1
