### ISSUE TITLE
can? method raises 'undefined method can? for Controller:Class'

### ISSUE THREAD

**Issue by ghost** [ryanb/cancan#115]
Hello,
I use the can? method to hide or show links in the views of my application and everything works fine. But in some places, I would like to do the same thing in the controller because views will be generated automatically by ActiveScaffold. So I have tried something like this:

<pre>
<code>
class WiffFilesController < ApplicationController
  load_and_authorize_resource
  active_scaffold :wiff_files
  unless can? :manage, WiffFile
    active_scaffold:wiff_files do |config|
      config.actions.exclude :update
      config.actions.exclude :delete
    end
  end
end
</code>
</pre>

However, this gets me an "undefined method `can?' for WiffFilesController:Class" error.

Could anyone help me identify what I'm doing wrong?
Thanks a lot!
Frederic

**Comment by Reyzapermanasaputra** [comment]
heyy yvanross thanks a lot for remember me :)
