### ISSUE TITLE
undefined method `can?' for #<#<Class:0x00000101e0cae8>:0x00000101e04e88>

### ISSUE THREAD

**Issue by sonymony** [ryanb/cancan#124]
I am using devise & cancan for authentication/authorization

I have had success with just devise but when I try to apply authorization with cancan I get errors

I do the following
1. create a user-role as suggested by http://www.tonyamoyal.com/2010/07/28/rails-authentication-with-devise-and-cancan-customizing-devise-controllers/

My models/ability.rb is as follows

<pre>
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # in case of guest
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end
</pre>

Then I update the views/articles.show.html.erb as such

<pre>
 <% if can? :update, @article %>
    <%= link_to "Edit", edit_article_path(@article) %>
  <% end %>
</pre>

Then when I go to http://localhost:3000/articles/1

I get the following error

<pre>
undefined method `can?' for #<#<Class:0x00000101e0cae8>:0x00000101e04e88>

Extracted source (around line #4):

1: <p id="notice"><%= notice %></p>
2: <%= render :partial =>@article%>
3: 
4:  <% if can? :update, @article %>
5:     <%= link_to "Edit", edit_article_path(@article) %>
6:   <% end %>
7: <%= link_to 'Back to Article..', articles_path %>
</pre>

Then when I add the follwoing to app/controllers/articles_controllers.rb

<pre>
load_and_authorize_resource
</pre>

as such 

<pre>
class ArticlesController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!, :except => [:show, :index]
</pre>

I get the following error at http://localhost:3000/

<pre>
undefined local variable or method `load_and_authorize_resource' for ArticlesController:Class
</pre>

Please help...
I have included
gem 'cancan' in Gemfile & have run the command $ bundle install
When I do Bundle Show... it says 
the follwoing as present
- cancan (1.3.2)
  - devise (1.1.1)

PLEASE help... I have been trying to solve this for 1 week..

**Comment by binhht-evolableasia** [comment]
Restart server rails, I will be work fine !
