### ISSUE TITLE
undefined local variable or method `current_user' for 

### ISSUE THREAD

**Issue by SomeWare** [ryanb/cancan#125]
Hi! I am using Devise and CanCan. I have setup Devise for the model *Member' and have setup CanCan's ability.rb with 'def initialize(member)'.

But I get this error message 'undefined local variable or method `current_user' for #RegionsController:0x00000102d44100'
for my controller when I put in 'load_and_authorize_resource' in my RegionsController.

If I comment out the line I get the same error message, but this time in the view with the 'if can?...'.

So, must one use the model 'User' at all time? Ifind 'Member' more appropriate in my case.

/Michael

**Comment by prdpspkt** [comment]
Hey, Ryanb, When I define the method you mentioned then I got the error as ghost did. Any other suggestions
