### ISSUE TITLE
Authorizing access to specific fields on a model

### ISSUE THREAD

**Issue by macek** [ryanb/cancan#154]
Cancan is my favorite authorization plugin for Rails but I seem to find difficulty when getting down to the nitty gritty. How would we go about role-based permissions for specific fields on any given model?

For example, say sales and customer service staff can edit the address fields on a user, but only admin or sales can update a user's customer number. Loading the user resource with cancan is no problem, but the field-based permission logic in the views get very ugly very quickly.

```
# e.g., app/views/users/_form.html.erb

<% if current_user.role?(:admin, :sales) %>
  <%= f.text_field :customer_number %>
<% else %>
  <%= @user.customer_number %>
<% end %>

<% if current_user.role?(:sales, :csr) %>
  <%# edit address fields %>
<% else %>
  <%# display address %>
<% end %>
```

This seems to be a very common issue I see people running into (myself included), but I'm never quite sure how to address it in the best way. If possible, I'd like to get a discussion going on this topic.

**Note:**  If it's not in cancan's scope, I completely understand closing this issue.

**Comment by ssoulless** [comment]
Hi, what happened with this? it seems to be abandoned, any new?

**Comment by Fedcomp** [comment]
@ssoulless use CanCanCan

**Comment by pedrocarmona** [comment]
reference new PR: https://github.com/CanCanCommunity/cancancan/pull/474
