### ISSUE TITLE
Skipping "authorize_resource" or "load_and_authorize_resource" method on inherited controllers

### ISSUE THREAD

**Issue by ghost** [ryanb/cancan#164]
Currently if your controllers inherit from an AdminController and you wish to put the <code>load_and_authorize_resource</code> in that AdminController, skipping that method on specific controllers is challenging. Any thoughts on clean ways to do this? I am still digging into the code an hope to provide some type of patch.

**Comment by sajjadmurtaza49** [comment]
Here is also a way.
load_and_authorize_resource :unless => :devise_controller?
