### ISSUE TITLE
How can I use CanCan on a controller without a companion Model?

### ISSUE THREAD

**Issue by rnhurt** [ryanb/cancan#22]
I have a calendar controller which builds and displays a calendar but there is no Calendar model.  When I use "load_and_authorize_resource" on the controller it fails with a "uninitialized constant" error.  I realize that I probably shouldn't use "load_and_authorize_resource" in this case but I don't really know how to get CanCan to secure the controller otherwise.

Am I missing something simple?
See: http://railscasts.com/episodes/192-authorization-with-cancan questions 42 & 44  for more detail and another viewpoint.

**Comment by bikonchou** [comment]
@ryanb It works!!! Thank you!

**Comment by covard** [comment]
@molte thank you so much for that, was banging my head against my desk.

**Comment by frostblooded** [comment]
When passing in symbols instead of a class, can you somehow pass a param, so that you can check if a condition is met in a block in the ability?
