### ISSUE TITLE
[Rails 3.0.1] can`t authorize model with name as "News'

### ISSUE THREAD

**Issue by jpascal** [ryanb/cancan#223]
[Rails 3.0.1] can`t authorize model with name as "News'

ability.rb:
...

can [:show, :index], News
...

news_conrtoller.rb:
class NewsController < ApplicationController
load_and_authorize_resource
layout "standart"
def index
@news = News.all
end
end

Recive message: You are not authorized to access this page.

**Comment by sadeeshkumarv** [comment]
I couldn't able to edit news and its failing since the action url in the form tag is not correct.
