### ISSUE TITLE
Error: uninitialized constant ApplicationController::CanCan

### ISSUE THREAD

**Issue by tscolari** [ryanb/cancan#28]
When I try to rake gems:install:

$ rake gems:install
(in /Users/tscolari/Projetos/skeleton)
rake aborted!
uninitialized constant ApplicationController::CanCan

(See full trace by running task with --trace)

**Comment by amfische** [comment]
talhait07 just put quotes around it

**Comment by YBoog** [comment]
You have to restart Puma.
