### ISSUE TITLE
Creating a singleton resource

### ISSUE THREAD

**Issue by ramontayag** [ryanb/cancan#452]
I have a User that `has_one :payment_profile`. Here's my routes config for that:

```
namespace :user do
  resource :payment_profile
end
```

To get to the `user/payment_profiles_controller#show`, the URL is: `/user/payment_profile`. That loads fine. However, when I try to create a payment profile (`POST` to `user_payment_profile_path`), I get this error:

```
undefined method `payment_profiles' for #<User:0x4b630b0>
```

When I comment out `load_and_authorize_resource`, it works fine. I'm using inherited_resources. It seems to me that by default, `load_and_authorize_resource`, upon creation, thinks the association is a `has_many`. I also tried `load_and_authorize_resource :singleton => true` but it doesn't work. Not sure if I used it the right way anyway.

To get around this, I just added `skip_load_and_authorize_resource :only => [:create]`.

**Comment by jmuheim** [comment]
This is really old, but maybe someone found a solution? My situation looks like this:

```
  # We can't rely on CanCanCan, as it relies on a params[:id] which isn't present, and by manually setting @user, the authorization isn't performed anymore. See
  def load_and_authorize_current_user
    @user = current_user
    authorize!(params[:action].to_sym, @user)
  end
```
