### ISSUE TITLE
Incorrect `current_user` for initialize?

### ISSUE THREAD

**Issue by neezer** [ryanb/cancan#467]
Running CanCan 1.6.5, Devise 1.4.5 and Rails 3.1.0

If I rescue from a `CanCan::AccessDenied` error and output the `current_user`, I get the email address of the user I signed in as. However, throwing in a `binding.pry` or `debugger` in the `initialize` method for `Ability` shows the passed in `user` as another user record (with no email address).

There are only two users in my database, and CanCan seems to want to only use the user with the lowest index (not the currently logged-in user).

What gives?

``` ruby
# app/controllers/application_controller.rb
rescue_from CanCan::AccessDenied do |exception|
  render :text => "Access denied for user #{current_user.email}." #=> correct current_user
end

# app/models/ability.rb
def initialize(user)
  binding.pry #=> user != current_user
  if user.admin?
    # ...
  end
end
```

The users in my DB:

```
pry(main)> User.all
=> [#<User id: 3, created_at: "2011-09-12 19:18:01", updated_at: "2011-09-12 19:18:01", device_id: "d509adfe611e2afb03aeab2155a1b9fe00e27e14", email: nil, encrypted_password: "", sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, authentication_token: nil, is_admin: false>,
 #<User id: 4, created_at: "2011-09-12 19:19:24", updated_at: "2011-09-12 19:24:19", device_id: "blahblahblah", email: "admin@example.com", encrypted_password: "$2a$10$JMbBrfm03uUnE/rPapmz8elJSFAKw4RV2hUkLRmeHn9N...", sign_in_count: 2, current_sign_in_at: "2011-09-12 19:24:19", last_sign_in_at: "2011-09-12 19:19:41", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", authentication_token: nil, is_admin: true>]
```

---

EDIT: Ok, I've narrowed this to an issue with `rails_admin` (https://github.com/sferik/rails_admin/pull/301). Seems to have this issue when trying to use `rails_admin`, but doing anything manually seems to work just fine.

**Comment by quantumpotato** [comment]
@neezer hey, what did you figure out? I've tried

```
  config.current_user_method { current_user }

  ## == Cancan ==
  config.authorize_with :cancan
```

but here

```
 def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
```

in ability, user is always nil.

**Comment by neezer** [comment]
@quantumpotato Sorry, might've waited too long to ask. Nine years later I'm no longer coding in Ruby and have no recollection what the solution was. 🤷‍♂️

Best of luck!
