### ISSUE TITLE
Stubbing ability when testing views with RSpec?

### ISSUE THREAD

**Issue by tborisova** [ryanb/cancan#602]
Hello, I am writing rspec tests for testing that a user with role "user" doesn't see the link "Edit User" so that it cannot edit other users but I get the error  undefined method `authenticate' for nil:NilClass.
I have this code:

<pre>
before(:each) do
 @user_b = FactoryGirl.create(:user, :email=>"foo@bar.bg", :password=>"132132132",
                             :password_confirmation=>"132132132", :id=>34534578687, :role=>"user")
end

describe "Edit link" do
  it "should see it if the page shows the profile of the current user" do   
    render
    rendered.should have_content(@user.email)
    rendered.should have_content(@user.role)
    rendered.should have_selector("a",:href=>"users/#{@user.id}/edit",:value=>"Edit")
  end                           
end
</pre>

and this is in shared_example and then in context "user is with role 'user'" I have this:

<pre>
@user = FactoryGirl.create(:user,:email=>"foo33@bar.bg",:password=>"132132132",    
                                        :password_confirmation=>"132132132",:id=>34534578686,:role=>"user")
            
ApplicationController.stub(:current_user).and_return(@user)
</pre>

but I get this error:

<pre>
 Failure/Error: render
     ActionView::Template::Error:
       undefined method `authenticate' for nil:NilClass
</pre>

I tried the things that are in here: https://github.com/ryanb/cancan/wiki/Testing-Abilities  but nothing worked. Has someone faced the same problem? 

Thanks in advance.

Update: Formatted the code and the description.

**Comment by jeffdlange** [comment]
Another viable possibility if this is for a view spec:
```
allow(view).to_receive(:can?).and_return(true)
```
Within that context, only run tests that `can?` should return `true`, then run a separate set of tests for if can? returns false.

**Comment by domangi** [comment]
> Another viable possibility if this is for a view spec:
> 
> ```
> context '[condition when can? should be true]' do
>   before { allow(view).to_receive(:can?).and_return(true) } # this is the key line
> 
>   it 'the test' do
>     # blah blah
>   end
> 
>   # etc
> 
> end
> ```
> 
> Within that context, only run tests that `can?` should return `true`, then run a separate set of tests for if `can?` returns `false` (e.g. one set of tests as if the user is a normal user, another for if the user is an admin).

there is a small typo @jeffdlange , it should be `allow(view).to receive(:can?).and_return(true)`, with a space between `to` and `receive`.

**Comment by jeffdlange** [comment]
Thanks @domangi 🙏, I updated my response to reflect your correction
