### ISSUE TITLE
CanCan cannot set privileges for devise models other than User

### ISSUE THREAD

**Issue by ghost** [ryanb/cancan#656]
Hi 

I'm using CanCan 1.6 with Ruby 1.9.2 and Rails 3.2.3. I've tried to setup different privileges for different devise models: User and Admin. This is what my Ability class looks like. But CanCan sets privileges only for the User model. Admin receives only guest privileges.

class Ability
    include CanCan::Ability

```
def initialize(model)
   case model
   when User
       can [:read, :edit] , :all
   when Admin
       can :manage, :all
   else
       can :read, :all
   end
end
```

end

**Comment by icyflame** [comment]
:+1:

This is really useful! Thanks @giniedp !
