### ISSUE TITLE
authorize_resource :class => false does not work

### ISSUE THREAD

**Issue by dlbock** [ryanb/cancan#944]
I have the following configuation:

![screen shot 2013-09-25 at 12 45 40 pm](https://f.cloud.github.com/assets/149529/1210955/20074856-2602-11e3-9797-c9b3699d7bf4.png)

![screen shot 2013-09-25 at 12 45 48 pm](https://f.cloud.github.com/assets/149529/1210957/2405aeca-2602-11e3-977d-03e509059c70.png)

![screen shot 2013-09-25 at 12 45 56 pm](https://f.cloud.github.com/assets/149529/1210961/29e80fae-2602-11e3-97f5-1ed1819c5e6b.png)

The only way I got it to work was to specifically call authorize! :index, :jobs, authorize! :trigger :jobs, etc on each action.

**Comment by 1v** [comment]
If you have `class: false` you can check controller name like that:
```ruby
'BackgroundDeploy'.underscore.split('/').last.singularize.to_sym
```
Or just pass symbol:
```ruby
load_and_authorize_resource class: :background_deploy
```
Or watch what can be passed:
https://github.com/ryanb/cancan/blob/4560928dc375f9b31de00381c98334eb6aabc4b9/lib/cancan/controller_resource.rb#L144-L151

Not documented at all.
