### ISSUE TITLE
Receive CanCan::AccessDenied error on first attempt to access resource after logging in with Devise

### ISSUE THREAD

**Issue by barriault** [ryanb/cancan#956]
I'm using the following in an app:

Ruby 2.0.0
Rails 4.0.1
CanCan 1.6.10
Devise 3.2.0

After signing in with Devise, the first time I attempt to access any CanCan protected resources, I get a CanCan::AccessDenied error. If I reload the page, it works fine. In my tests I'm seeing the same behavior. The first test that attempts to access a CanCan protected resource always fails.

**Comment by euveng** [comment]
Worked for me. Thanks mate!
